security:
    encoders:
        App\Entity\Person:
            algorithm: auto

    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        # used to reload user from session & other features (e.g. switch_user)
        app_user_provider:
            entity:
                class: App\Entity\Person
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            user_checker: App\Security\UserChecker
            anonymous: ~
            provider: app_user_provider
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            remember_me:
                secret:   '%kernel.secret%'
                remember_me_parameter: login[remember_me]
                lifetime: 604800 # 1 week in seconds
                path: /
            logout:
                path: app_logout
                # where to redirect after logout
                # target: app_any_route

            # activate different ways to authenticate
            # https://symfony.com/doc/current/security.html#firewalls-authentication

            # https://symfony.com/doc/current/security/impersonating_user.html
            # switch_user: true

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/sentEmail, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/verify//, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/request_reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/request_processed, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/new_password, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        # - { path: ^/admin, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }
